title: Prisma Pop
email: contato@prismapop.com
description: Aproximamos o Brasil da Ásia com serviços de tradução e interpretação de Japonês-Português, organização de eventos, relações B2B, contratação de artistas do leste asiático, produção artística, pesquisa de mercado, e consultoria.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://prismapop.com"

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
